name: HTTPRequests
version: '${version}'
main: org.lactusplugins.mc.httprequests.HTTPRequests
api-version: 1.15
authors: [ Lactus ]
description: Sending HTTP requests from minecraft
website: https://github.com/KactusG
commands:
  httprequests:
    usage: /httprequests
    aliases: [hr]
